### ISSUE TITLE
good practices in real statistical/ecological projects

### ISSUE THREAD

**Issue by gabrielareto** [forestgeo/learn#21]
this is a list of suggested basic good practices in real projects like those of CTFS:

version control for data and code
- copy, then touch
- a version is a copy with a unique name
- don't use the f word ("final") on the file names
- use dates in the file names
- use git and github if you can
- record R version, packages versions

automation
- touch the script, not the console.
- write and edit, don't try to remember a sequence of clicks etc
- don't touch raw data
- don't touch processed data
- don't touch figures
- don't touch the text if you can avoid it

separated directories in self-contained projects
- raw vs processed data
- typical directories: raw data, processed data, scripts, results
(figures, tables), text (manually updated), other directories?

document
- humans do read scripts
- use English
- use at least raw text
- use other tools if you can (Rmarkdown etc)

good practices for coding or programming are a different story, see issue #17 . But, in general, a typical script could look like this:

1) erase everything
2) tell where the stuff is
3) set the seed and maybe other general parameters (e.g. date for
version control)
4) load functionality
5) load data
6) review and clean data
7) do interesting things
8) keep results

this script-level structure is much more subjective and
project-dependent than the other things, though.

What do you think?

**Comment by maurolepore** [comment]
👍

**Comment by maurolepore** [comment]
@gabrielareto,
Ups, I realized that is issue is similar to #17. Shall I move this  content there?

**Comment by gabrielareto** [comment]
probably.
also #13 and #8

**Comment by gabrielareto** [comment]
I moved to #17
